- config.json
- docs/Software Architecture Document/History/index.md
- docs/Software Architecture Document/Table of Contents/index.md
Added changes and approves history
Related issue(s): APPLINK-26662, APPLINK-26096
> Add History chapter

- docs/Software Architecture Document/Operational View/index.md
Added log4cxx features short description
Update to opensource links
Related issue(s): APPLINK-26662, APPLINK-26096, APPLINK-26781
> Diagnostics update

- config.json
- docs/Software Architecture Document/History/index.md
- docs/Software Architecture Document/Table of Contents/index.md
Added history for #5, #7, #8 and #10 changes.
*Note:* This branch base on changes from #9.
> Update History for august 2016 changes

- docs/Software Architecture Document/Development View/index.md
- docs/Software Architecture Document/History/index.md
- docs/Software Architecture Document/References/index.md
Update Development View, References, History
Related issue(s): APPLINK-26096, APPLINK-26662
> Change Coding style for Core

- docs/Software Architecture Document/Components View/index.md
- docs/Software Architecture Document/History/index.md
Changed BT connection limitation to the 30.
Related issue(s): APPLINK-26096, APPLINK-26662
> Update BT connection limitation

- docs/Overview/index.md
Add links for easy navigation for SAD.
Related issue(s): APPLINK-26096
> Update Overview with links

- docs/ATF/Table of Contents/index.md
- docs/Software Architecture Document/Table of Contents/index.md
Related issue(s): APPLINK-16160, APPLINK-16192
> Add names for Table of contents

- docs/Software Architecture Document/History/index.md
Related issue : [APPLINK-31310](https://adc.luxoft.com/jira/browse/APPLINK-31310)
> Add RC changes history point

- docs/Software Architecture Document/Components View/index.md
- docs/Software Architecture Document/Introduction/index.md
> Move Rev components to Applicaiton manager Layer

- docs/Video Streaming Setup/index.md
> Update Video Streaming Guide with RTP information

- docs/Video Streaming Setup/index.md
Adding in a missing link to Android Video Streaming docs
> Add link to android video streaming

- config.json
- docs/Encryption Setup/index.md
- Steps include generating a self signed certificate
- Configuring Core files
- Configuring policy table to enable rpc message encryption feature
> Add guide for setting up RPC message encryption

- config.json
- docs/FAQ/index.md
- docs/Getting Started/INI Configuration/index.md
- docs/Getting Started/Install and Run/index.md
- docs/Getting Started/index.md
- docs/Overview/index.md
Created a guide for setting up the SDL Core project from scratch
> Add getting started guide using information from Core README

- config.json
- docs/Overview/index.md
- docs/Remote Control Guide/index.md
Rough draft of an RC overview guide linking out to more specific documentation.
All feedback appreciated!
> initial rc guide

- docs/Multiple Transports Configuration/index.md
> Fix Typo in Multiple Transports Configuration

- config.json
- docs/Doxygen Inline Documentation/index.md
- docs/Overview/index.md
added a link to the doxygen generated inline documentation
> add doxygen inline docs

- docs/Feature Documentation/App Service Provider Guide/index.md
Fixes https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/issues/200.
Adds a note regarding enabling the embedded nav service as an app service provider.
> Embedded nav app service best practice

- docs/Feature Documentation/RPC Encryption/index.md
- docs/Overview/index.md
Also fix name of Smart Objects section
> Fix broken link in Overview

- docs/Feature Documentation/App Service Guidelines/index.md
- docs/Feature Documentation/Remote Control/index.md
- docs/Feature Documentation/Service Status Update/index.md
- docs/Integrating Your HMI/Developing the HMI UI/index.md
- docs/Integrating Your HMI/SDL Core and HMI Communication/index.md
- docs/Integrating Your HMI/SDL Core and HMI Communication/index_zh-hans.md
- docs/Integrating Your HMI/Vehicle Data/index.md
update links to hmi integration guidelines since they were moved into the core guides
> fix hmi integration guidelines links

- docs/Integrating Your HMI/Developing the HMI UI/index.md
Updates developing HMI UI guide to include note about nested submenus and driver distraction menu limits.
> Additional submenu depth and driver distraction

- docs/Integrating Your HMI/Developing the HMI UI/index.md
Update documentation to reflect changes from the feature https://github.com/smartdevicelink/sdl_core/issues/2788
> Feature/Supported Character Sets

- docs/Integrating Your HMI/Developing the HMI UI/index.md
Add notes to ui development guide about dynamic menu capabilities.
> Add notes aboute dynamic menus

- docs/Integrating Your HMI/SDL Core and HMI Communication/index.md
make more clear the usage of each hmi result structure, add example WARNINGS with info response from HMI
> clarify hmi response structures, add example warnings w info

- docs/Integrating Your HMI/SDL Core and HMI Communication/index.md
Note it is necessary for the hmi to respond to the GetSystemInfo request.
> Add GetSystemInfo information

- docs/Integrating Your HMI/SDL Core and HMI Communication/index.md
Add note about the required capability responses the hmi must send at startup
> Add note about required capability responses

- docs/Feature Documentation/Audio and Video Streaming/index.md
Now both HMIs support streaming
HMI no longer requires code modifications to stream
> hmis now support some in browser streaming

- config.json
- docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.0 to 7.1/index.md
- docs/Overview/index.md
Add guide for migrating from core 7.0 to core 7.1
> Feature/Migrating from 7.0 to 7.1
